### ISSUE TITLE
Link on title of plugin in plugin dashboard takes you to personal site

### ISSUE THREAD

**Issue by thesunshade** [shantanugoel/joplin-plugin-cm-linenumbers#6]
Now the link in the plugin dashboard for the plugin takes you to shantanugoel.com. It should really take you to the github repository or a page dedicated to the plugin, I think.

![image](https://user-images.githubusercontent.com/82448383/130318629-1d32e6f9-57f6-49ff-a784-03b79e20136d.png)

This change needs to be made here: https://github.com/shantanugoel/joplin-plugin-cm-linenumbers/blob/main/src/manifest.json

**Comment by shantanugoel** [comment]
Fixed in 225c1abe2147ebbd5f307897546194cbb1ac71fe

**Comment by thesunshade** [comment]
Thanks! Can confirm it works.
