### ISSUE TITLE
Add the plugin to the Joplin plugin repository

### ISSUE THREAD

**Issue by thesunshade** [shantanugoel/joplin-plugin-cm-linenumbers#7]
From the [forum page](https://discourse.joplinapp.org/t/plugin-to-enable-line-numbers/12735) the plugin already has more than 300 click-throughs. It would be great if it could be added to the official plugin repository.

Instructions for adding to the repository are here: https://discourse.joplinapp.org/t/official-joplin-plugin-repository-is-now-ready-if-you-are-developing-a-plugin-please-read-on/13635

Thanks for the great plugin!

**Comment by shantanugoel** [comment]
Made the release on github. Will publish on npm/joplin repository by tomorrow (Made an error while publishing and npm requires to wait for 24 hours)

**Comment by thesunshade** [comment]
Thank you!

**Comment by shantanugoel** [comment]
Published here https://www.npmjs.com/package/joplin-plugin-codemirror-line-numbers I think it should be picked up by joplin repository soon.

**Comment by thesunshade** [comment]
Great!
